#!/bin/bash
set -e
set -x

#npm install --save probmods/webppl webppl-timeit@latest webppl-dp@latest agentmodels/webppl-agents null-a/webppl-nn
npm install
cd node_modules/webppl
npm install
grunt bundle:../webppl-timeit:../webppl-dp:../webppl-agents:../webppl-nn
cd ../webppl-editor
npm install
grunt bundle
grunt uglify
cd ../webppl-viz
npm install
grunt bundle
grunt uglify
cd ../..
cp node_modules/webppl/bundle/webppl.min.js assets/js/webppl.min.js
cp node_modules/webppl-editor/docs/webppl-editor.min.js assets/js/webppl-editor.min.css
cp node_modules/webppl-editor/docs/webppl-editor.css assets/css/webppl-editor.css
cp node_modules/webppl-viz/docs/webppl-viz.min.js assets/js/webppl-viz.min.css
cp node_modules/webppl-viz/docs/webppl-viz.css assets/css/webppl-viz.css
echo "Success."
